### ISSUE TITLE
Backgrounding `w` 

### ISSUE THREAD

**Issue by jeversmann** [NosotrosNueces/utcs-uptime#4]
After reading through the features of a few scheduling libraries, I propose adding [agenda](https://github.com/rschmukler/agenda) to the app to work out scheduling for the requests to each server in a configurable way. Agenda will want Mongo, which gives us something towards #3, although we were expecting to use Mongo anyway.

**Comment by jeversmann** [comment]
This was pulled into master a while ago, but follow-up question:

Should Agenda run as part of the server or as a separate process? They currently need to be run separately.

**Comment by JDong820** [comment]
lol can we makefile it, i.e. 
`make start`
`make test`
`make reload`
I would like that.

**Comment by jeversmann** [comment]
We're not gonna makefile it. Apparently you can't put arbitrary scripts into npm like that (`npm db` didn't work for me) but what I'm asking is if the server process should handle the jobs as well, less memory/code overhead and fewer failure points/logs to read.

**Comment by JDong820** [comment]
yes. Modular better. Just have the server check that the thing is running, and error if the data service is not running.

**Comment by jeversmann** [comment]
> yes

You say that, but then disagree with me.

We don't benefit from modularity if we put unnecessary dependencies between the two like that check, which would prevent us from something like splitting the work across machines. I want to stop having separate modules and get rid of our strange implicit dependency on the other service.

**Comment by JDong820** [comment]
I was only considering modularity in that the data pulling code would be physically separate from the data handling code. If you want to assume that the data pulling code is always running, that's fine.
